### ISSUE TITLE
Corrupted file `GazeboStlExport.py`

### ISSUE THREAD

**Issue by galou** [maidenone/RobotCreator#2]
Hi,

when trying out your module, I encountered an error in `GazeboStlExport.py`, l.95: `sdfFile.close()nyArm/"+obj.Name+".stl"\n'))`. I guess this happened while saving.

Thanks!
Gaël

**Comment by maidenone** [comment]
This was caused by some Indentation issues. The file was created from sdfExport.FCMacro and had some issues. Also made ithe project path based on current username rather then hardcoded path to my home dir. It will export the files to your ~/.gazebo/models/ directory by default with robot name "testing", Robot name and project path can only be configured in the file for now.  

The FCMacro files are most up to date and are being "ported" over to the actual workbench as its easier/quicker to debug/develop with the FCMacro files rather then the full workbench integration.
